# bash run.sh
conda activate v4_pytorch1.11
#python3 test.py --data data/dataset/FloW_IMG/FloW_IMG.yaml --names data/dataset/FloW_IMG/FloW_IMG.name --verbose --weights /home/HardDisk/61075029h/YOLO/train/FloW_IMG-MTSYOLO/weights/best.pt --cfg models/cfg/MTSYOLO-single.cfg
#python3 test.py --data data/dataset/FloW_IMG/FloW_IMG.yaml --names data/dataset/FloW_IMG/FloW_IMG.name --verbose --weights /home/HardDisk/61075029h/YOLO/train/FloW_IMG-YOLOv4/weights/best.pt --cfg models/cfg/YOLOv4_single.cfg
#python3 test.py --data data/dataset/FloW_IMG/FloW_IMG.yaml --names data/dataset/FloW_IMG/FloW_IMG.name --verbose --weights /home/HardDisk/61075029h/YOLO/train/FloW_IMG-TSYOLO/weights/best.pt --cfg models/cfg/yolov4-ts-single.cfg
#python3 test.py --data data/dataset/FloW_IMG/FloW_IMG.yaml --names data/dataset/FloW_IMG/FloW_IMG.name --verbose --weights /home/HardDisk/61075029h/YOLO/train/FloW_IMG_SFYOLO_ori_1002/weights/best.pt --cfg models/cfg/MTSYOLO-lite-sf.cfg
#python3 test.py --data data/dataset/FloW_IMG/FloW_IMG.yaml --names data/dataset/FloW_IMG/FloW_IMG.name --verbose --weights /home/HardDisk/61075029h/YOLO/train/MTSYOLO_lite_100/weights/best.pt --cfg models/cfg/MTSYOLO-lite.cfg
#python3 test.py --data data/dataset/FloW_IMG/FloW_IMG.yaml --verbose --weights /home/HardDisk/61075029h/YOLO/train/FloW_IMG-RTSYOLO13/weights/best.pt --cfg models/cfg/RTSYOLO-single.cfg
#python3 detect.py --source /home/usera/Downloads/YOLOv4_WongKinYiu/data/dataset/FloW_IMG/Sequence_1.avi --weights /home/HardDisk/61075029h/YOLO/train/MTSYOLO_lite_100/weights/best.pt --cfg models/cfg/MTSYOLO-lite.cfg --names /home/usera/Downloads/YOLOv4_WongKinYiu/data/dataset/FloW_IMG/FloW_IMG.name
#python3 detect.py --source /home/usera/Downloads/YOLOv4_WongKinYiu/data/dataset/FloW_IMG/Sequence_1.avi --weights /home/HardDisk/61075029h/YOLO/train/FloW_IMG-RTSYOLO13/weights/best.pt --cfg models/cfg/RTSYOLO-single.cfg --names /home/usera/Downloads/YOLOv4_WongKinYiu/data/dataset/FloW_IMG/FloW_IMG.name